Cross.Web/Models/Cars/EditViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Cross.Web.Models.Cars
{
    public class EditViewModel
    {
        public int? Id { get; set; }

        public int UserId { get; set; }

        [Display(Name = "Номер автомобиля")]
        public string LicensePlate { get; set; }

        [Display(Name = "Вид заезда")]
        public int RaceTypeId { get; set; }

        [Display(Name = "Класс автомобиля")]
        public int DisciplineId { get; set; }
    }
}

Cross.Web/Models/Events/EditViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Cross.Web.Models.Events
{
    public class EditViewModel
    {
        public int? Id { get; set; }

        [Display(Name = "Место проведения")]
        public int VenueId { get; set; }

        [Display(Name = "Вид")]
        public int RaceTypeId { get; set; }

        public bool? IsCancelled { get; set; }

        [Display(Name = "Дата начала")]
        [DataType(DataType.Date)]
        public DateTime DateStart { get; set; }

        [Display(Name = "Дата окончания")]
        [DataType(DataType.Date)]
        public DateTime DateEnd { get; set; }
    }
}

Cross.Web/Models/Events/IndexViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Cross.Web.Models.Events
{
    public class IndexViewModel
    {
        public int Id { get; set; }

        [Display(Name ="Место проведения")]
        public string Venue { get; set; }

        [Display(Name = "Вид")]
        public string RaceType { get; set; }

        public bool IsCancelled { get; set; }

        [Display(Name = "Дата")]
        [DataType(DataType.Date)]
        public DateTime DateStart { get; set; }

        [DataType(DataType.Date)]
        public DateTime DateEnd { get; set; }
    }
}

Cross.Web/Models/Races/EditViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Cross.Web.Models.Races
{
    public class EditViewModel
    {
        public int? Id { get; set; }

        [Display(Name = "Дата и время")]
        public DateTime DateTime { get; set; }

        public bool? IsCancelled { get; set; }

        [Display(Name = "Вид")]
        public int RaceStatusId { get; set; }

        [Display(Name = "Класс")]
        public int DisciplineId { get; set; }

        public int EventId { get; set; }
        [Display(Name = "Трасса")]

        public int TrackId { get; set; }
    }
}

Cross.Web/Models/Requests/EditViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Cross.Web.Models.Requests
{
    public class EditViewModel
    {
        public int RequestId { get; set; }

        public int ActionId { get; set; }

        [Display(Name = "Комментарий подтверждающего")]
        public string Comment { get; set; }
    }
}

Cross.Web/Controllers/EventsController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Cross.Model;
using Cross.BLL.Managers;
using Cross.Web.Models.Events;
using Microsoft.AspNetCore.Authorization;
using Cross.BLL.Enums;

namespace Cross.Web.Controllers
{
    [Authorize(Roles = Roles.User)]
    public class EventsController : Controller
    {
        private readonly CancellationDbEntityManager<Event> _eventManager;
        private readonly DbEntityManager<RaceType>_raceTypeManager;
        private readonly DbEntityManager<Venue>_venueManager;

        public EventsController(CancellationDbEntityManager<Event> eventManager, DbEntityManager<RaceType> raceTypeManager, DbEntityManager<Venue> venueManager)
        {
            _eventManager = eventManager;
            _raceTypeManager = raceTypeManager;
            _venueManager = venueManager;
        }

        public IActionResult Index()
        {
            var events = _eventManager.GetAll();
            var indexViewModels = events.Select(e => new IndexViewModel()
            {
                Id = e.Id,
                Venue = e.Venue.Name,
                RaceType = e.RaceType.Name,
                IsCancelled = e.IsCancelled,
                DateStart = e.DateStart,
                DateEnd = e.DateEnd
            });
            return View(indexViewModels);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                ViewData["RaceTypeId"] = new SelectList(_raceTypeManager.GetAll(), "Id", "Name");
                ViewData["VenueId"] = new SelectList(_venueManager.GetAll(), "Id", "Name");
                return View();
            }

            var @event = _eventManager.Find(id.Value);
            if (@event == null)
            {
                return NotFound();
            }
            var editViewModel = new EditViewModel()
            {
                Id = @event.Id,
                VenueId = @event.VenueId,
                RaceTypeId = @event.RaceTypeId,
                IsCancelled = @event.IsCancelled,
                DateStart = @event.DateStart,
                DateEnd = @event.DateEnd
            };
            ViewData["RaceTypeId"] = new SelectList(_raceTypeManager.GetAll(), "Id", "Name", editViewModel.RaceTypeId);
            ViewData["VenueId"] = new SelectList(_venueManager.GetAll(), "Id", "Name", editViewModel.VenueId);
            return View(editViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(EditViewModel editViewModel)
        {
            if (ModelState.IsValid)
            {
                _eventManager.Save(new Event()
                {
                    Id = editViewModel.Id ?? 0,
                    VenueId = editViewModel.VenueId,
                    RaceTypeId = editViewModel.RaceTypeId,
                    IsCancelled = editViewModel.IsCancelled??false,
                    DateStart = editViewModel.DateStart,
                    DateEnd = editViewModel.DateEnd
                });
                return RedirectToAction(nameof(Index));
            }
            ViewData["RaceTypeId"] = new SelectList(_raceTypeManager.GetAll(), "Id", "Name", editViewModel.RaceTypeId);
            ViewData["VenueId"] = new SelectList(_venueManager.GetAll(), "Id", "Name", editViewModel.VenueId);
            return View(editViewModel);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            _eventManager.Remove(id.Value);

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Cancel(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            _eventManager.Cancel(id.Value);

            return RedirectToAction("Index");
        }
    }
}

Cross.Web/Controllers/RacesController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Cross.Model;
using Cross.Web.Models.Races;
using Cross.BLL.Managers;

namespace Cross.Web.Controllers
{
    public class RacesController : Controller
    {
        private readonly RaceManager _raceManager;
        private readonly DbEntityManager<Discipline> _disciplineManager;
        private readonly DbEntityManager<RaceStatus> _raceStatusManager;
        private readonly DbEntityManager<Track> _trackManager;

        public RacesController(RaceManager raceManager, DbEntityManager<Discipline> disciplineManager, DbEntityManager<RaceStatus> raceStatusManager, DbEntityManager<Track> trackManager)
        {
            _raceManager = raceManager;
            _disciplineManager = disciplineManager;
            _raceStatusManager = raceStatusManager;
            _trackManager = trackManager;
        }

        public IActionResult Index(int? eventId)
        {
            if (eventId == null)
            {
                return NotFound();
            }

            var races = _raceManager.GetRacesByEventId(eventId.Value);

            var indexViewModels = races.Select(r => new IndexViewModel()
            {
                Id = r.Id,
                DateTime = r.DateTime,
                IsCancelled = r.IsCancelled,
                RaceStatus = r.RaceStatus.Name,
                Discipline = r.Discipline.Name,
                EventId = r.EventId,
                Track = r.Track.Name
            });

            ViewData["EventId"] = eventId;
            return View(indexViewModels);
        }

        public IActionResult Create(int? eventId)
        {
            if (eventId == null)
            {
                return NotFound();
            }

            ViewData["DisciplineId"] = new SelectList(_disciplineManager.GetAll(), "Id", "Name");
            ViewData["RaceStatusId"] = new SelectList(_raceStatusManager.GetAll(), "Id", "Name");
            ViewData["TrackId"] = new SelectList(_trackManager.GetAll(), "Id", "Name");
            return View("Edit", new EditViewModel() {EventId = (int)eventId });
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var race = _raceManager.Find(id.Value);

            if (race == null)
            {
                return NotFound();
            }

            var editViewModel = new EditViewModel()
            {
                Id = race.Id,
                DateTime = race.DateTime,
                IsCancelled = race.IsCancelled,
                RaceStatusId = race.RaceStatusId,
                DisciplineId = race.DisciplineId,
                EventId = race.EventId,
                TrackId = race.TrackId
            };

            ViewData["DisciplineId"] = new SelectList(_disciplineManager.GetAll(), "Id", "Name", editViewModel.DisciplineId);
            ViewData["RaceStatusId"] = new SelectList(_raceStatusManager.GetAll(), "Id", "Name", editViewModel.RaceStatusId);
            ViewData["TrackId"] = new SelectList(_trackManager.GetAll(), "Id", "Name", editViewModel.TrackId);

            return View(editViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(EditViewModel editViewModel)
        {
            if (ModelState.IsValid)
            {
                _raceManager.Save(new Race()
                {
                    Id = editViewModel.Id ?? 0,
                    DateTime = editViewModel.DateTime,
                    IsCancelled = editViewModel.IsCancelled ?? false,
                    RaceStatusId = editViewModel.RaceStatusId,
                    DisciplineId = editViewModel.DisciplineId,
                    EventId = editViewModel.EventId,
                    TrackId = editViewModel.TrackId
                });
                return RedirectToAction(nameof(Index),new {editViewModel.EventId});
            }

            ViewData["DisciplineId"] = new SelectList(_disciplineManager.GetAll(), "Id", "Name", editViewModel.DisciplineId);
            ViewData["RaceStatusId"] = new SelectList(_raceStatusManager.GetAll(), "Id", "Name", editViewModel.RaceStatusId);
            ViewData["TrackId"] = new SelectList(_trackManager.GetAll(), "Id", "Name", editViewModel.TrackId);

            return View(editViewModel);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventId = _raceManager.Find(id.Value).EventId;

            _raceManager.Remove(id.Value);

            return RedirectToAction("Index", new { eventId });
        }

        public IActionResult Cancel(int? eventId, int? raceId)
        {
            if (eventId == null || raceId == null)
            {
                return NotFound();
            }

            _raceManager.Cancel(raceId.Value);

            return RedirectToAction("Index", new { eventId });
        }
    }
}

Cross.Web/Views/Events/Edit.cshtml
@model Cross.Web.Models.Events.EditViewModel

    <h3>Мероприятия</h3>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="IsCancelled" />
            <div class="form-group">
                <label asp-for="VenueId" class="control-label"></label>
                <select asp-for="VenueId" class="form-control" asp-items="ViewBag.VenueId"></select>
                <span asp-validation-for="VenueId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RaceTypeId" class="control-label"></label>
                <select asp-for="RaceTypeId" class="form-control" asp-items="ViewBag.RaceTypeId"></select>
                <span asp-validation-for="RaceTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateStart" class="control-label"></label>
                <input asp-for="DateStart" class="form-control" />
                <span asp-validation-for="DateStart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateEnd" class="control-label"></label>
                <input asp-for="DateEnd" class="form-control" />
                <span asp-validation-for="DateEnd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-outline-secondary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Cross.Web/Views/Events/Index.cshtml
@model IEnumerable<Cross.Web.Models.Events.IndexViewModel>

    <h3 align="center">Мероприятия</h3>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.DateStart)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Venue)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RaceType)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @if (item.IsCancelled)
                        {
                            <strike>
                                @Html.DisplayFor(modelItem => item.DateStart) - @Html.DisplayFor(modelItem => item.DateEnd)
                            </strike>
                        }
                        else
                        {
                            <span>
                                @Html.DisplayFor(modelItem => item.DateStart) - @Html.DisplayFor(modelItem => item.DateEnd)
                            </span>
                        }

                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Venue)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RaceType)
                    </td>
                    <td>
                        @if (User.IsInRole(Roles.EventManager))
                        {
                        <a class="btn btn-sm btn-outline-secondary" asp-action="Edit" asp-route-id="@item.Id">Изменить</a>
                        <a class="btn btn-sm btn-outline-secondary" asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
                        <a class="btn btn-sm btn-outline-secondary" asp-action="Cancel" asp-route-id="@item.Id">
                            @if (item.IsCancelled)
                            {
                                <span>Сделать активным</span>
                            }
                            else
                            {
                                <span>Отменить</span>
                            }
                        </a>
                        }
                        <a class="btn btn-sm btn-outline-secondary" asp-controller="Races" asp-action="Index" asp-route-eventId="@item.Id">Посмотреть заезды</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
@if (User.IsInRole(Roles.EventManager))
{
    <div align="center">
        <p>
            <a class="btn btn-lg btn-outline-secondary" asp-action="Edit">Создать мероприятие</a>
        </p>
    </div>
}