Cross.Web/Models/Cars/ChooseСarViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Cross.Web.Models.Cars
{
    public class BasicCarInfoViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Номер автомобиля")]
        public string LicensePlate { get; set; }
    }

    public class ChooseСarViewModel
    {
        public int RaceId { get; set; }

        public int ActionId { get; set; }

        public List<BasicCarInfoViewModel> Cars { get; set; }
    }
}

Cross.Web/Models/Cars/DetailsViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Cross.Web.Models.Cars
{
    public class DetailsViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Номер автомобиля")]
        public string LicensePlate { get; set; }

        [Display(Name = "Вид заезда")]
        public string RaceType { get; set; }

        [Display(Name = "Класс автомобиля")]
        public string Discipline { get; set; }
    }
}

Cross.Web/Models/Cars/EditViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Cross.Web.Models.Cars
{
    public class EditViewModel
    {
        public int? Id { get; set; }

        public int UserId { get; set; }

        [Display(Name = "Номер автомобиля")]
        public string LicensePlate { get; set; }

        [Display(Name = "Вид заезда")]
        public int RaceTypeId { get; set; }

        [Display(Name = "Класс автомобиля")]
        public int DisciplineId { get; set; }
    }
}

Cross.Web/Models/Events/EditViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Cross.Web.Models.Events
{
    public class EditViewModel
    {
        public int? Id { get; set; }

        [Display(Name = "Место проведения")]
        public int VenueId { get; set; }

        [Display(Name = "Вид")]
        public int RaceTypeId { get; set; }

        public bool? IsCancelled { get; set; }

        [Display(Name = "Дата начала")]
        [DataType(DataType.Date)]
        public DateTime DateStart { get; set; }

        [Display(Name = "Дата окончания")]
        [DataType(DataType.Date)]
        public DateTime DateEnd { get; set; }
    }
}

Cross.Web/Models/Races/EditViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Cross.Web.Models.Races
{
    public class EditViewModel
    {
        public int? Id { get; set; }

        [Display(Name = "Дата и время")]
        public DateTime DateTime { get; set; }

        public bool? IsCancelled { get; set; }

        [Display(Name = "Вид")]
        public int RaceStatusId { get; set; }

        [Display(Name = "Класс")]
        public int DisciplineId { get; set; }

        public int EventId { get; set; }
        [Display(Name = "Трасса")]

        public int TrackId { get; set; }
    }
}

Cross.Web/Models/Requests/EditViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Cross.Web.Models.Requests
{
    public class EditViewModel
    {
        public int RequestId { get; set; }

        public int ActionId { get; set; }

        [Display(Name = "Комментарий подтверждающего")]
        public string Comment { get; set; }
    }
}

Cross.Web/Controllers/CarsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Cross.Model;
using Cross.Web.Models.Cars;
using Cross.BLL.Managers;
using Microsoft.AspNetCore.Authorization;
using Cross.BLL.Enums;
using Microsoft.AspNetCore.Identity;
using System.Linq;
using System.Threading.Tasks;

namespace Cross.Web.Controllers
{
    [Authorize(Roles = Roles.User)]
    public class CarsController : Controller
    {
        private readonly CarManager _carManager;
        private readonly DbEntityManager<RaceType> _raceTypeManager;
        private readonly DbEntityManager<Discipline> _disciplineManager;
        private readonly UserManager<User> _userManager;
        private readonly RaceManager _raceManager;

        public CarsController(CarManager carManager, DbEntityManager<RaceType> raceTypeManager, DbEntityManager<Discipline> disciplineManager,
            UserManager<User> userManager, RaceManager raceManager)
        {
            _carManager = carManager;
            _raceTypeManager = raceTypeManager;
            _disciplineManager = disciplineManager;
            _userManager = userManager;
            _raceManager = raceManager;
        }

        public IActionResult Create(int? userId)
        {
            if (userId == null)
                return NotFound();

            ViewData["DisciplineId"] = new SelectList(_disciplineManager.GetAll(), "Id", "Name");
            ViewData["RaceTypeId"] = new SelectList(_raceTypeManager.GetAll(), "Id", "Name");
            return View(nameof(Edit), new EditViewModel() { UserId = (int)userId });
        }

        public IActionResult Edit(int? carId)
        {
            if (carId == null)
                return NotFound();

            var car = _carManager.Find(carId.Value);
            var editViewModel = new EditViewModel()
            {
                Id = car.Id,
                LicensePlate = car.LicensePlate,
                DisciplineId = car.DisciplineId,
                RaceTypeId = car.RaceTypeId,
                UserId = car.UserId
            };

            ViewData["DisciplineId"] = new SelectList(_disciplineManager.GetAll(), "Id", "Name");
            ViewData["RaceTypeId"] = new SelectList(_raceTypeManager.GetAll(), "Id", "Name");
            return View(editViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(EditViewModel editViewModel)
        {
            if (_carManager.ExistLicensePlate(editViewModel.LicensePlate, editViewModel.RaceTypeId, editViewModel.DisciplineId))
                ModelState.AddModelError("LicensePlate", "Такой номер уже существует");

            if (ModelState.IsValid)
            {
                _carManager.Save(new Car()
                {
                    Id = editViewModel.Id ?? 0,
                    UserId = editViewModel.UserId,
                    LicensePlate = editViewModel.LicensePlate,
                    RaceTypeId = editViewModel.RaceTypeId,
                    DisciplineId = editViewModel.DisciplineId
                });
                return RedirectToAction("Index", "Users");
            }

            ViewData["DisciplineId"] = new SelectList(_disciplineManager.GetAll(), "Id", "Name", editViewModel.DisciplineId);
            ViewData["RaceTypeId"] = new SelectList(_raceTypeManager.GetAll(), "Id", "Name", editViewModel.RaceTypeId);

            return View(editViewModel);
        }

        public async Task<IActionResult> ChooseСarAsync(int? raceId, int? actionId)
        {
            if (raceId == null || actionId == null)
                return NotFound();

            var race = _raceManager.Find(raceId.Value);
            var user = await _userManager.GetUserAsync(User);
            var viewModel = new ChooseСarViewModel
            {
                RaceId = raceId.Value,
                ActionId = actionId.Value,
                Cars = user.Cars.Where(c=>c.DisciplineId == race.DisciplineId)
                .Select(c => new BasicCarInfoViewModel
                {
                    Id = c.Id,
                    LicensePlate = c.LicensePlate
                }).ToList()
            };
            return View(viewModel);

        }

        public IActionResult Delete(int carId, int userId)
        {
            _carManager.Remove(carId);

            return RedirectToAction("Details", "Users", new { userId });
        }
    }
}

Cross.Web/Controllers/RequestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Cross.Model;
using Cross.BLL.Enums;
using Cross.Web.Models.Requests;
using Microsoft.AspNetCore.Identity;
using Cross.BLL.Managers;
using Microsoft.AspNetCore.Authorization;
using System.Threading.Tasks;

namespace Cross.Web.Controllers
{
    [Authorize(Roles = Roles.User)]
    public class RequestsController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly ActionManager _actionManager;
        private readonly RequestManager _requestManager;

        public RequestsController(UserManager<User> userManager, ActionManager actionManager, RequestManager requestManager)
        {
            _userManager = userManager;
            _actionManager = actionManager;
            _requestManager = requestManager;
        }

        public async Task<IActionResult> IndexAsync()
        {
            var user = await _userManager.GetUserAsync(User);
            var requests = new List<Request>();

            if (User.IsInRole(Roles.Administrator))
                requests = _requestManager.GetAll().ToList();
            else
                requests = _requestManager.GetRequestsByCars(user.Cars).ToList();

            var indexViewModels = new List<IndexViewModel>();
            foreach (var request in requests)
            {
                var requestUser = _userManager.Users.FirstOrDefault(u => u.Cars.Any(c => c.Id == request.CarId));
                indexViewModels.Add(new IndexViewModel()
                {
                    RequestId = request.Id,
                    DateTime = request.Race.DateTime,
                    Discipline = request.Race.Discipline.Name,
                    RaceStatus = request.Race.RaceStatus.Name,
                    RaceType = request.Race.Event.RaceType.Name,
                    Track = request.Race.Track.Name,
                    Venue = request.Race.Event.Venue.Name,
                    User = requestUser.UserName,
                    LicensePlate = request.Car.LicensePlate,
                    Status = request.Status.Name,
                    Created = request.Created,
                    Modifed = request.Modifed,
                    Actions = _actionManager.GetActions(user.Id, request.StatusId).ToDictionary(a => a.Id, a => a.NameMUI),
                    Comment = request.Comment
                });
            }
            return View(indexViewModels);
        }

        public async Task<IActionResult> DetailsAsync(int? raceId)
        {
            if (raceId == null)
                return NotFound();

            var user = await _userManager.GetUserAsync(User);
            var requests = new List<Request>();

            if (User.IsInRole(Roles.Administrator))
                requests = _requestManager.GetRequestsByRaceId(raceId.Value).ToList();
            else
                requests = _requestManager.GetRequestsByRaceIdAndCars(raceId.Value, user.Cars).ToList();

            var indexViewModels = new List<IndexViewModel>();
            foreach (var request in requests)
            {
                var requestUser = _userManager.Users.FirstOrDefault(u => u.Cars.Any(c => c.Id == request.CarId));
                indexViewModels.Add(new IndexViewModel()
                {
                    RequestId = request.Id,
                    DateTime = request.Race.DateTime,
                    Discipline = request.Race.Discipline.Name,
                    RaceStatus = request.Race.RaceStatus.Name,
                    RaceType = request.Race.Event.RaceType.Name,
                    Track = request.Race.Track.Name,
                    Venue = request.Race.Event.Venue.Name,
                    User = requestUser.UserName,
                    LicensePlate = request.Car.LicensePlate,
                    Status = request.Status.Name,
                });
            }
            return View(indexViewModels);
        }

        public IActionResult Create(int? carId ,int? raceId, int? actionId)
        {
            if (carId == null || raceId == null || actionId == null)
                return NotFound();

            var action = _actionManager.Find(actionId.Value);

            var request = new Request()
            {
                Id = 0,
                CarId = carId.Value,
                RaceId = raceId ?? 0,
                StatusId = action.SetStatusId,
                Created = DateTime.Now,
                Modifed = DateTime.Now,
            };
            _requestManager.Save(request);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int? requestId, int? actionId)
        {
            if (requestId == null || actionId == null)
            {
                return NotFound();
            }

            var editViewModel = new EditViewModel()
            {
                RequestId = requestId.Value,
                ActionId = actionId.Value
            };
            return View(editViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int? requestId, int? actionId, string comment)
        {
            if (requestId == null || actionId == null)
            {
                return NotFound();
            }

            var request = _requestManager.Find(requestId.Value);
            var action = _actionManager.Find(actionId.Value);
            request.StatusId = action.SetStatusId;
            request.Modifed = DateTime.Now;
            request.Comment = comment;

            _requestManager.Save(request);
            return RedirectToAction("Index");
        }
    }
}

Cross.Web/Views/Cars/ChooseСar.cshtml
@model Cross.Web.Models.Cars.ChooseСarViewModel
@{
    ViewData["Title"] = "Details";
}

<div align="center">
    <div class="col-md-4 mx-auto">
        <h3>Выберите парковочное место</h3>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">@Html.DisplayNameFor(model => model.Cars.FirstOrDefault().LicensePlate)</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Cars)
                {
                    <tr>
                        <td>@item.LicensePlate</td>
                        <td>
                            <a class="btn btn-outline-secondary" asp-controller="Requests" asp-action="Create" asp-route-carId="@item.Id" asp-route-raceId="@Model.RaceId" asp-route-actionId="@Model.ActionId">Выбрать</a><br />
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Cross.Web/Views/Cars/Edit.cshtml
@model Cross.Web.Models.Cars.EditViewModel



<div class="col-md-4 mx-auto">
    <h3>Добавить автомобиль</h3>
    <form asp-action="Edit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="UserId" />
        <div class="form-group">
            <label asp-for="LicensePlate" class="control-label"></label>
            <input asp-for="LicensePlate" class="form-control" />
            <span asp-validation-for="LicensePlate" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="RaceTypeId" class="control-label"></label>
            <select asp-for="RaceTypeId" class="form-control" asp-items="ViewBag.RaceTypeId"></select>
            <span asp-validation-for="RaceTypeId" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="DisciplineId" class="control-label"></label>
            <select asp-for="DisciplineId" class="form-control" asp-items="ViewBag.DisciplineId"></select>
            <span asp-validation-for="DisciplineId" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Сохранить" class="btn btn-outline-secondary" />
        </div>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Cross.Web/Views/Cars/List.cshtml
@model IEnumerable<Cross.Web.Models.Cars.DetailsViewModel>

<table class="table">
    <thead>
        <tr>
            <th scope="col">@Html.DisplayNameFor(model => model.LicensePlate)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.Discipline)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.RaceType)</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>@item.LicensePlate</td>
            <td>@item.Discipline</td>
            <td>@item.RaceType</td>
            <td><a class="blog-header-logo text-black-50" asp-controller="Cars" asp-action="Edit" asp-route-id="@item.Id">Изменить</a></td>
            <td><a class="blog-header-logo text-black-50" asp-controller="Cars" asp-action="Delete" asp-route-id="@item.Id">Удалить</a></td>
        </tr>
        }
    </tbody>
</table>